# ECE2112

Miguel Joaquin T. Cariño 2 ECE-D

# PROGRAMMING ASSIGNMENT 2


In [10]:
import numpy as np

# A. REPRODUCIBLE NORMALIZATION PROBLEM

In [11]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5,5))
Mean = np.mean(X)
STD = np.std(X)
X_normalized = (X-Mean)/STD
NormM = np.mean(X_normalized)
NormS = np.std(X_normalized)
print("X-Normalized:")
print(X_normalized)
print(" ")
print("X:")
print(X)
print(" ")
print("Mean:")
print(Mean)
print(" ")
print("Standard Deviation:")
print(STD)
print(" ")
print("X-Normalized Mean:")
print(NormM)
print(" ")
print("X-Normalized STD:")
print(NormS)
np.save("X_normalized.npy", X_normalized)

X-Normalized:
[[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]
 
X:
[[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]
 
Mean:
46.36
 
Standard Deviation:
25.864075471588002
 
X-Normalized Mean:
0.0
 
X-Normalized STD:
0.9999999999999999


# B. CUBES DIVISIBLE BY 4 PROBLEM

In [12]:
A = np.arange(1,101)
B = A*A*A
C = B.reshape(10,10)
div_by_4 = C[C % 4 ==0]
print("Shape of C")
print(C.shape)
print(" ")
print("div_by_4:")
print(div_by_4)
print(" ")
print("Number of Elemets:")
print(len(div_by_4))
np.save("div_by_4.npy", div_by_4)


Shape of C
(10, 10)
 
div_by_4:
[      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]
 
Number of Elemets:
50


# C. ABOVE-MEAN SQUARES

In [13]:
S = np.arange(1, 37)
S = S*S
S = S.reshape(6,6)
S_mean = S.mean()
above_mean = S[S > S_mean]
print ("S:")
print (S)
print (" ")
print ("Mean:")
print (S_mean)
print (" ")
print ("Above Mean:")
print (above_mean)
print(" ")
print ("Number of Elements:")
print (len(above_mean))
np.save("above_mean.npy", above_mean)

S:
[[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]
 
Mean:
450.1666666666667
 
Above Mean:
[ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]
 
Number of Elements:
15
